# Generated by Django 5.2.7 on 2026-01-12 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_dailyactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyactivity',
            name='recurrence',
            field=models.CharField(choices=[('none', 'None'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='dailyactivity',
            name='recurrence_end',
            field=models.DateField(blank=True, help_text='Optional end date for recurrence', null=True),
        ),
        migrations.AddField(
            model_name='dailyactivity',
            name='recurrence_interval',
            field=models.PositiveIntegerField(default=1, help_text='Interval for recurrence (e.g., every N days/weeks/months)'),
        ),
    ]
