# Generated by Django 5.2.7 on 2026-01-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyactivity',
            name='last_completed_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
