# Generated by Django 5.2.7 on 2026-01-12 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_assigned_caregiver_user_assigned_doctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alzheimers_duration_years',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Duration of Alzheimer's in years", null=True),
        ),
    ]
