# Generated by Django 5.2.7 on 2026-01-14 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_alzheimers_duration_years'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='caregiving_experience_years',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Years of caregiving experience', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='relationship_to_patient',
            field=models.CharField(blank=True, help_text='Relationship to patient (e.g. Spouse)', max_length=100, null=True),
        ),
    ]
