# Generated by Django 5.2.7 on 2026-02-25 04:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_caregiving_experience_years_user_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caregiver',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
        ),
        migrations.RenameField(
            model_name='user',
            old_name='assigned_doctor',
            new_name='doctor',
        ),
        migrations.RemoveField(
            model_name='user',
            name='assigned_caregiver',
        ),
        migrations.AddField(
            model_name='user',
            name='caregiver',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'CAREGIVER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_patients', to=settings.AUTH_USER_MODEL),
        ),
    ]
