# Generated by Django 5.2.7 on 2026-02-25 04:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_caregiver_patient_rename_assigned_doctor_user_doctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='behaviour_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='cognitive_risk',
            field=models.CharField(choices=[('Low Risk', 'Low Risk'), ('Moderate Risk', 'Moderate Risk'), ('High Risk', 'High Risk')], default='Low Risk', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='health_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='memory_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='caregiver',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'CAREGIVER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caregiver_patients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='doctor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'DOCTOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_patients', to=settings.AUTH_USER_MODEL),
        ),
    ]
