# Generated by Django 4.2.7 on 2026-02-26 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_behaviour_score_user_cognitive_risk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='caregiver',
            field=models.ForeignKey(blank=True, help_text='The Caregiver assigned to this Patient', limit_choices_to={'role': 'CAREGIVER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_patients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='doctor',
            field=models.ForeignKey(blank=True, help_text='The Doctor responsible for this user (Doctor/Caregiver/Patient)', limit_choices_to={'role': 'DOCTOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
